# Generated by Django 3.2 on 2025-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_checkbox_checkbox_allvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
