# Generated by Django 3.2 on 2025-03-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_checkbox_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='allVals',
            new_name='language',
        ),
    ]
